site_name: Excel Tutorial
nav:
  - Home: index.md
  - Creating A Budget: Task1.md
  - Setting Up A Chart: Task2.md
  - Making A CheckList: Task3.md
  - TroubleShooting: TroubleShooting.md
  - Glossary: Glossary.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
